import Sidebar from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Box from "@mui/material/Box";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={rubik.className} lang="en">
      <body
        style={{
          maxWidth: "100vw",
          height: "100%",
          backgroundImage: "url(/Background.jpg)",
          backgroundAttachment: "scroll",
          backgroundRepeat: "no-repeat",
          marginBlock: "30px",
          marginInline: "20px"
        }}
      >
        <Box width={"100%"} display={"flex"}>
          <Sidebar />
          {children}
        </Box>
      </body>
    </html>
  );
}
